
export CXX=g++
export CC=gcc
export LEPINJSPACE=/home/nwkamp/Research/CCM/DipoleAnalysis
export LEPINJBUILDPATH=$LEPINJSPACE/local
export LEPINJSOURCEPATH=$LEPINJSPACE/sources/LeptonInjectorDevPrivate/
export PREFIX=$LEPINJBUILDPATH
export PATH=$LEPINJBUILDPATH/bin:$PATH
export LD_LIBRARY_PATH=$LEPINJBUILDPATH/lib/:$LD_LIBRARY_PATH
export LD_LIBRARY_PATH=$LEPINJBUILDPATH/lib64/:$LD_LIBRARY_PATH
export C_INCLUDE_PATH=$LEPINJBUILDPATH/include/:$C_INCLUDE_PATH
export CPLUS_INCLUDE_PATH=$LEPINJBUILDPATH/include/:$CPLUS_INCLUDE_PATH
export CXX_INCLUDE_PATH=$LEPINJBUILDPATH/include/:$CPLUS_INCLUDE_PATH
export PKG_CONFIG_PATH=$LEPINJBUILDPATH/lib/pkgconfig:$PKG_CONFIG_PATH
export PYTHONPATH=$LEPINJBUILDPATH/lib/python2.7/site-packages:$PYTHONPATH
#export PYTHONPATH=$LEPINJBUILDPATH/lib64:$PYTHONPATH
# hack
mkdir $LEPINJBUILDPATH $LEPINJSOURCEPATH
